### ISSUE TITLE
--in-path Requirement

### ISSUE THREAD

**Issue by marioahner** [jzftran/jws2txt#6]
Hi when I use the jws2txt command I get the following output. This is maybe a naive question but why dosen't it work? 

jws2txt /Users/test.jws 

usage: jws2txt [-h] --in-path IN_PATH [--out-dir OUT_DIR]
               [--delimiter DELIMITER] [--comments {True,False}]
               [--header {True,False}]
jws2txt: error: the following arguments are required: --in-path

**Comment by jzftran** [comment]
Hi,
try running jws2txt --in-path /Users/test.jws

I hope it helps, if not, let me know
cheers
Jozef

pt., 24 lis 2023 o 16:02 marioahner ***@***.***> napisał(a):

**Comment by marioahner** [comment]
Hi,
thanks for the help, now I don't get the "--in-path" error anymore but it returns the following without converting the file:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/jws2txt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jws2txt/jws2txt.py", line 51, in main
    JWSFile(path=jws_file_path).write_data(out_file=out_file_path,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jws2txt/helpers/helpers.py", line 48, in __init__
    file = ofio.olefile.OleFileIO(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/olefile/olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/olefile/olefile.py", line 1192, in open
    self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/olefile/olefile.py", line 1105, in _raise_defect
    raise exception_type(message)
OSError: not an OLE2 structured storage file


FYI: I use MacOS Sonoma v14.1.1 and I aquired the .jws-Files using a Jasco J-715 and SpectraManager on a Win 2000 PC

Cheers,

Phil

**Comment by hjwijma** [comment]
Hi,
 
It happens that I got get essentially the same error message as Phil while using Rocky linux 9.3.


To my surprise, it turned out the software was fine but somehow the files had been damaged earlier. When I obtained fresh files from the PhD student, it worked fine, for some 1200 files in total.

The files were absorption traces from a JASCO V660.
 
Cheers,
Hein

**Comment by heliosight** [comment]
Hi, when I use the software I get the following output. The file is not corrupt and can be opened by original Jasco software.
Do you have any ideas on how this could be fixed?

Thanks,
Igor

igia0001@client195-169 ~ % jws2txt --in-path /Users/igia0001/Downloads/test2.jws
Traceback (most recent call last):
  File "/Users/igia0001/Library/Python/3.12/bin/jws2txt", line 5, in <module>
    from jws2txt.jws2txt import main
  File "/Users/igia0001/Library/Python/3.12/lib/python/site-packages/jws2txt/__init__.py", line 1, in <module>
    from .helpers.helpers import JWSFile  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igia0001/Library/Python/3.12/lib/python/site-packages/jws2txt/helpers/helpers.py", line 3, in <module>
    import olefile as ofio
ModuleNotFoundError: No module named 'olefile'
igia0001@client195-169 ~ %

**Comment by jzftran** [comment]
The error message you're seeing indicates that the Python module 'olefile' is not installed on your system. This module is a dependency for the jws2txt package you're trying to use. Here's how you can resolve this issue:
 Install the missing module:
Open your terminal and run the following command:
pip install olefile

This will install the olefile module, which is required by jws2txt.
 If you're using a virtual environment, make sure you've activated it before running the pip install comman
If you still encounter issues, you might want to ensure that jws2txt and all its dependencies are properly installed. You can do this by reinstalling jws2txt:
pip uninstall jws2txt
pip install jws2txt

If you continue to have issues after trying these steps, please provide more information about your Python environment and how you installed jws2txt initially.

Józef Tran

> Wiadomość napisana przez heliosight ***@***.***> w dniu 05.07.2024, o godz. 15:36:
> 
> ***@***.*** ~ % jws2txt --in-path /Users/igia0001/Downloads/test2.jws
> Traceback (most recent call last):
> File "/Users/igia0001/Library/Python/3.12/bin/jws2txt", line 5, in 
> from jws2txt.jws2txt import main
> File "/Users/igia0001/Library/Python/3.12/lib/python/site-packages/jws2txt/init.py", line 1, in 
> from .helpers.helpers import JWSFile # noqa: F401
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/Users/igia0001/Library/Python/3.12/lib/python/site-packages/jws2txt/helpers/helpers.py", line 3, in 
> import olefile as ofio
> ModuleNotFoundError: No module named 'olefile'
> ***@***.*** ~ %

**Comment by yujinaitoh** [comment]
Hello.

My work directry 
./work/jwsfiles/mesureddata.jws
./work/outoput/

cd work
 jws2txt --in-path C:\Users\myname\Desktop\work\jwsfiles\mesureddata.jws --out-dir C:\Users\myname\Desktop\work\output

then, I got no message or response, only my current directry was diplayed.
The process appeared to be successful, but no files were created in the output folder.

Do you have any advises about my problem?

**Comment by jzftran** [comment]
Hello @yujinaitoh 
It looks like the tool expects a directory for --in-path, not a single file.
Right now you’re pointing it directly to:
C:\Users\myname\Desktop\work\jwsfiles\mesureddata.jws
So the tool likely scans the path, sees it isn’t a folder, and exits without processing anything (hence no error and no output).
Try running it like this instead:
`jws2txt --in-path C:\Users\myname\Desktop\work\jwsfiles --out-dir C:\Users\myname\Desktop\work\output`
This way it can iterate over all .jws files in the folder and generate the converted files into output.
If it still produces nothing, the next things to verify would be:


that the .jws file extension is exactly .jws (no hidden .JWS/double extension)


that the output directory exists beforehand


that you have read/write permissions for both folders

Cheers
Jóżef
